# Generated by Django 2.2 on 2020-02-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_vehicle_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='lastServiceDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchaseDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
